version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    container_name: nextjs-app
    depends_on:
      - postgres-db
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://user:password@postgres-db:5432/mydb"  # Update here
    command: ["/bin/sh", "-c", "npx prisma migrate deploy && npm start"]
    restart: always  # This will restart the app if it fails


volumes:
  postgres-data:
